In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:

dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
inde=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
inde

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [6]:
dep=dataset[['classification_yes']]
dep

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [7]:
dataset['classification_yes'].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
inde= sc.fit_transform(inde)
inde= sc.transform(inde)

In [13]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
param_grid={'criterion':['gini','entropy','log_loss'],'max_features':[None,'sqrt','log2'],'n_estimators':[10,50,100]}
grid=GridSearchCV(RandomForestClassifier(),param_grid,verbose=1,n_jobs=-1,refit=True,cv=5)
grid.fit(inde,dep)

Fitting 5 folds for each of 27 candidates, totalling 135 fits

C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [10, 50, 100]},
             verbose=1)

In [14]:
re=grid.cv_results_
print("best_parameters:",format(grid.best_params_))
grid_predictions=grid.predict(inde)

best_parameters: {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}

In [15]:
from sklearn.metrics import f1_score
f1_macro=f1_score(dep,grid_predictions,average="weighted")
print("the the best f1_scores parameter{}:",format(grid.best_params_)),f1_score

the the best f1_scores parameter{}: {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}

(None,
 <function sklearn.metrics._classification.f1_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>)

In [16]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(dep,grid_predictions)

In [17]:
print("confusion matrix:\n",cm)

confusion matrix:
 [[150   0]
 [  0 249]]

In [18]:
from sklearn.metrics import classification_report
clf_report=classification_report(dep,grid_predictions)

In [19]:

print("claf report:\n",clf_report)

claf report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       150
           1       1.00      1.00      1.00       249

    accuracy                           1.00       399
   macro avg       1.00      1.00      1.00       399
weighted avg       1.00      1.00      1.00       399

In [20]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.039845,0.008460,0.003127,6.253147e-03,gini,None,10,"{'criterion': 'gini', 'max_features': None, 'n...",0.4875,0.9750,0.9375,0.9750,0.987342,0.872468,0.193210,27
1,0.164339,0.016658,0.010274,2.577077e-03,gini,None,50,"{'criterion': 'gini', 'max_features': None, 'n...",0.5000,0.9750,0.9625,0.9875,0.987342,0.882468,0.191457,26
2,0.319625,0.024998,0.015623,8.583069e-07,gini,None,100,"{'criterion': 'gini', 'max_features': None, 'n...",0.5125,0.9750,0.9750,0.9875,0.987342,0.887468,0.187566,25
3,0.058577,0.021628,0.002152,2.013773e-03,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.9750,1.0000,0.9750,0.9875,0.822785,0.952057,0.065297,24
4,0.089391,0.007652,0.012378,6.193406e-03,gini,sqrt,50,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.9250,1.0000,0.9875,0.9875,1.000000,0.980000,0.028062,6
5,0.193638,0.007487,0.015623,7.008046e-07,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.9250,1.0000,0.9750,0.9875,1.000000,0.977500,0.027839,11
6,0.049995,0.011691,0.006249,7.653838e-03,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.8875,0.9750,0.9875,0.9750,1.000000,0.965000,0.039843,16
7,0.087490,0.012498,0.012498,6.249118e-03,gini,log2,50,"{'criterion': 'gini', 'max_features': 'log2', ...",0.9375,1.0000,0.9750,0.9875,1.000000,0.980000,0.023184,6
8,0.187479,0.009881,0.012499,6.249404e-03,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.9375,1.0000,0.9875,0.9875,1.000000,0.982500,0.023184,2
9,0.031247,0.000000,0.003124,6.248951e-03,entropy,None,10,"{'criterion': 'entropy', 'max_features': None,...",0.8875,1.0000,0.9375,0.9750,0.987342,0.957468,0.040751,20
10,0.149984,0.015932,0.009374,7.653682e-03,entropy,None,50,"{'criterion': 'entropy', 'max_features': None,...",0.8750,0.9875,0.9375,0.9875,1.000000,0.957500,0.046503,19
11,0.262472,0.015307,0.012499,6.249356e-03,entropy,None,100,"{'criterion': 'entropy', 'max_features': None,...",0.8750,0.9750,0.9375,0.9875,1.000000,0.955000,0.045139,22
12,0.021873,0.007654,0.009374,7.653955e-03,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.8750,0.9875,0.9750,0.9875,1.000000,0.965000,0.045689,15
13,0.087491,0.007654,0.006249,7.653955e-03,entropy,sqrt,50,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.9375,1.0000,0.9875,0.9875,1.000000,0.982500,0.023184,2
14,0.181230,0.007654,0.012499,6.249619e-03,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.9250,1.0000,0.9875,0.9875,1.000000,0.980000,0.028062,6
15,0.018748,0.006249,0.006249,7.653546e-03,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.9000,1.0000,0.9875,1.0000,1.000000,0.977500,0.039051,11
16,0.084365,0.007654,0.015624,1.093611e-06,entropy,log2,50,"{'criterion': 'entropy', 'max_features': 'log2...",0.9375,1.0000,0.9875,0.9875,1.000000,0.982500,0.023184,2
17,0.183165,0.012767,0.015980,4.661077e-04,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.9625,1.0000,0.9750,0.9875,1.000000,0.985000,0.014577,1
18,0.043746,0.011692,0.009374,7.653994e-03,log_loss,None,10,"{'criterion': 'log_loss', 'max_features': None...",0.9250,0.9875,0.9375,0.9750,0.974684,0.959937,0.024200,18
19,0.139482,0.015254,0.015733,2.001451e-04,log_loss,None,50,"{'criterion': 'log_loss', 'max_features': None...",0.8750,0.9750,0.9375,0.9875,1.000000,0.955000,0.045139,22
20,0.280849,0.020919,0.009374,7.653955e-03,log_loss,None,100,"{'criterion': 'log_loss', 'max_features': None...",0.9125,0.9750,0.9375,0.9875,1.000000,0.962500,0.032596,17
21,0.032648,0.011138,0.006226,7.625366e-03,log_loss,sqrt,10,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.8750,0.9875,0.9750,0.9875,0.962025,0.957405,0.042268,21
22,0.087938,0.007449,0.015623,6.975526e-07,log_loss,sqrt,50,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.9375,1.0000,0.9750,0.9875,1.000000,0.980000,0.023184,6
23,0.187646,0.017184,0.009427,7.698134e-03,log_loss,sqrt,100,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.9375,0.9875,0.9750,0.9875,1.000000,0.977500,0.021506,11
24,0.031225,0.017135,0.003124,6.248951e-03,log_loss,log2,10,"{'criterion': 'log_loss', 'max_features': 'log...",0.9500,0.9875,0.9875,0.9875,1.000000,0.982500,0.016956,2
25,0.103114,0.007653,0.009374,7.653838e-03,log_loss,log2,50,"{'criterion': 'log_loss', 'max_features': 'log...",0.9250,1.0000,0.9750,0.9875,1.000000,0.977500,0.027839,11
26,0.172764,0.017535,0.009573,7.818648e-03,log_loss,log2,100,"{'criterion': 'log_loss', 'max_features': 'log...",0.9250,1.0000,0.9875,0.9875,1.000000,0.980000,0.028062,6

In [23]:
from sklearn.metrics import roc_auc_score

roc_auc_score(dep,grid.predict_proba(inde)[:,1])

1.0

In [24]:
Future_Prediction=grid.predict([[0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]