In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('Social_Network_Ads.csv')

In [3]:
dataset.head(133)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
128  15722758    Male   30            17000          0
129  15792102  Female   26            84000          0
130  15675185    Male   31            58000          0
131  15801247    Male   33            31000          0
132  15725660    Male   30            87000          0

[133 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0         True
1    15810944   35            20000          0         True
2    15668575   26            43000          0        False
3    15603246   27            57000          0        False
4    15804002   19            76000          0         True
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1        False
396  15706071   51            23000          1         True
397  15654296   50            20000          1        False
398  15755018   36            33000          0         True
399  15594041   49            36000          1        False

[400 rows x 5 columns]

In [6]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [9]:
from sklearn.ensemble import RandomForestClassifier

In [10]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': [None,'sqrt','log2'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train_, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [11]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [12]:
print(grid.best_params_)

{'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 100}

In [13]:
table=pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.043995,0.003493,0.012271,0.003562,gini,None,10,"{'criterion': 'gini', 'max_features': None, 'n...",0.800000,0.842105,0.780488,0.878049,0.888889,0.837906,0.042337,6
1,0.366227,0.027227,0.035204,0.004768,gini,None,100,"{'criterion': 'gini', 'max_features': None, 'n...",0.727273,0.777778,0.809524,0.850000,0.918919,0.816699,0.064994,9
2,0.040407,0.002364,0.009157,0.001960,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.727273,0.810811,0.750000,0.842105,0.894737,0.804985,0.060877,12
3,0.368685,0.022942,0.032194,0.001645,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.764706,0.871795,0.809524,0.900000,0.923077,0.853820,0.058576,4
4,0.038471,0.013248,0.011814,0.006400,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.823529,0.810811,0.780488,0.871795,0.918919,0.841108,0.048781,5
5,0.376132,0.010802,0.026761,0.001247,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.800000,0.871795,0.809524,0.900000,0.923077,0.860879,0.048707,3
6,0.046878,0.010884,0.011474,0.001706,entropy,None,10,"{'criterion': 'entropy', 'max_features': None,...",0.687500,0.810811,0.809524,0.850000,0.888889,0.809345,0.067570,11
7,0.388846,0.007085,0.031758,0.004004,entropy,None,100,"{'criterion': 'entropy', 'max_features': None,...",0.764706,0.789474,0.809524,0.850000,0.894737,0.821688,0.045979,8
8,0.041925,0.004037,0.007286,0.000956,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.687500,0.820513,0.809524,0.871795,0.944444,0.826755,0.084389,7
9,0.345906,0.008702,0.024970,0.006557,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.800000,0.871795,0.809524,0.900000,0.947368,0.865737,0.055418,1
10,0.041278,0.003491,0.009658,0.003393,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.687500,0.810811,0.780488,0.900000,0.888889,0.813538,0.077639,10
11,0.260921,0.008678,0.012734,0.006369,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.800000,0.871795,0.809524,0.900000,0.947368,0.865737,0.055418,1

In [15]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 100}: 0.9256751954513147

In [16]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[79  6]
 [ 4 45]]

In [17]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.95      0.93      0.94        85
           1       0.88      0.92      0.90        49

    accuracy                           0.93       134
   macro avg       0.92      0.92      0.92       134
weighted avg       0.93      0.93      0.93       134

In [18]:
age_input=float(input("Age:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:32
Sex Male 0 or 1:0
Smoker Yes 0 or 1:0

In [19]:
Future_Prediction=grid.predict([[age_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]