In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:

dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
inde=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
inde

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [6]:
dep=dataset[['classification_yes']]
dep

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [7]:
dataset['classification_yes'].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
inde= sc.fit_transform(inde)

In [12]:
from sklearn.model_selection import GridSearchCV 
from sklearn.svm import SVC
param_grid={'kernel':['rbf','sigmoid','poly'],'C':[10,1000,2000,3000,4000] ,'gamma':['auto','scale']}
grid=GridSearchCV(SVC(probability=True),param_grid,refit=True,verbose=2,n_jobs=-1,cv=5)
grid.fit(inde,dep)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=5, estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10, 1000, 2000, 3000, 4000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'sigmoid', 'poly']},
             verbose=2)

In [13]:
re=grid.cv_results_
print("best_parameters:",format(grid.best_params_))
grid_predictions=grid.predict(inde)

best_parameters: {'C': 10, 'gamma': 'auto', 'kernel': 'poly'}

In [14]:
from sklearn.metrics import roc_auc_score

roc_auc_score(dep,grid.predict_proba(inde)[:,1])

1.0

In [15]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(dep,grid_predictions)

In [16]:
print("confusion matrix:\n",cm)

confusion matrix:
 [[150   0]
 [  0 249]]

In [17]:
from sklearn.metrics import classification_report
clf_report=classification_report(dep,grid_predictions)

In [18]:

print("claf report:\n",clf_report)

claf report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       150
           1       1.00      1.00      1.00       249

    accuracy                           1.00       399
   macro avg       1.00      1.00      1.00       399
weighted avg       1.00      1.00      1.00       399

In [19]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.027390,0.004360,0.006591,0.005935,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.9250,0.9875,1.0000,1.0000,0.987342,0.979968,0.028054,3
1,0.022583,0.005086,0.010934,0.006168,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.9125,0.9875,1.0000,1.0000,0.987342,0.977468,0.032968,5
2,0.053163,0.010162,0.013574,0.006492,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.9500,0.9875,1.0000,1.0000,0.987342,0.984968,0.018367,1
3,0.030117,0.006404,0.016194,0.000549,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.9250,0.9875,1.0000,1.0000,0.987342,0.979968,0.028054,3
4,0.029709,0.006572,0.008921,0.007344,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.9125,0.9875,1.0000,1.0000,0.987342,0.977468,0.032968,5
5,0.051768,0.008562,0.014834,0.006513,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.9500,0.9875,1.0000,1.0000,0.987342,0.984968,0.018367,1
6,0.027675,0.007181,0.011213,0.002681,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.9125,0.9875,1.0000,1.0000,0.987342,0.977468,0.032968,5
7,0.028444,0.005199,0.008676,0.004654,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.8125,0.9750,0.9875,0.9875,1.000000,0.952500,0.070445,23
8,0.050761,0.013944,0.012565,0.004384,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.8875,0.9750,0.9875,1.0000,0.974684,0.964937,0.039828,15
9,0.026585,0.004804,0.011711,0.006765,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.9125,0.9875,1.0000,1.0000,0.987342,0.977468,0.032968,5
10,0.024841,0.005215,0.013183,0.006796,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.8125,0.9750,0.9875,0.9875,1.000000,0.952500,0.070445,23
11,0.049907,0.007788,0.017542,0.006278,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.8875,0.9750,0.9875,1.0000,0.974684,0.964937,0.039828,15
12,0.024156,0.007100,0.012507,0.006254,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.9125,0.9875,1.0000,1.0000,0.987342,0.977468,0.032968,5
13,0.023004,0.006725,0.015267,0.005515,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.8125,0.9750,0.9875,0.9875,1.000000,0.952500,0.070445,23
14,0.052495,0.012237,0.010157,0.006188,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.8875,0.9750,0.9875,1.0000,0.974684,0.964937,0.039828,15
15,0.024904,0.006563,0.014493,0.002761,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.9125,0.9875,1.0000,1.0000,0.987342,0.977468,0.032968,5
16,0.028649,0.004423,0.010557,0.005726,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",0.8125,0.9750,0.9875,0.9875,1.000000,0.952500,0.070445,23
17,0.041929,0.006742,0.017306,0.003719,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.8875,0.9750,0.9875,1.0000,0.974684,0.964937,0.039828,15
18,0.030617,0.003815,0.012250,0.006615,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.9125,0.9875,1.0000,1.0000,0.987342,0.977468,0.032968,5
19,0.025352,0.008668,0.015235,0.001625,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.8125,0.9750,0.9875,0.9875,1.000000,0.952500,0.070445,23
20,0.040592,0.006804,0.013409,0.006716,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.8875,0.9750,0.9875,1.0000,0.974684,0.964937,0.039828,15
21,0.020433,0.005148,0.011916,0.006064,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.9125,0.9875,1.0000,1.0000,0.987342,0.977468,0.032968,5
22,0.027226,0.006477,0.015852,0.005656,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",0.8125,0.9750,0.9875,0.9875,1.000000,0.952500,0.070445,23
23,0.049918,0.010461,0.012521,0.007318,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.8875,0.9750,0.9875,1.0000,0.974684,0.964937,0.039828,15
24,0.030784,0.005049,0.013319,0.003186,4000,auto,rbf,"{'C': 4000, 'gamma': 'auto', 'kernel': 'rbf'}",0.9125,0.9875,1.0000,1.0000,0.987342,0.977468,0.032968,5
25,0.024547,0.005157,0.016151,0.004793,4000,auto,sigmoid,"{'C': 4000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.8125,0.9750,0.9875,0.9875,1.000000,0.952500,0.070445,23
26,0.054618,0.009033,0.009359,0.003284,4000,auto,poly,"{'C': 4000, 'gamma': 'auto', 'kernel': 'poly'}",0.8875,0.9750,0.9875,1.0000,0.974684,0.964937,0.039828,15
27,0.034189,0.005492,0.014822,0.003869,4000,scale,rbf,"{'C': 4000, 'gamma': 'scale', 'kernel': 'rbf'}",0.9125,0.9875,1.0000,1.0000,0.987342,0.977468,0.032968,5
28,0.026109,0.010254,0.009431,0.006138,4000,scale,sigmoid,"{'C': 4000, 'gamma': 'scale', 'kernel': 'sigmo...",0.8125,0.9750,0.9875,0.9875,1.000000,0.952500,0.070445,23
29,0.040643,0.006070,0.012588,0.006294,4000,scale,poly,"{'C': 4000, 'gamma': 'scale', 'kernel': 'poly'}",0.8875,0.9750,0.9875,1.0000,0.974684,0.964937,0.039828,15